# Generated by Django 3.0.6 on 2020-06-05 06:23

from django.db import migrations, models
import django.db.models.deletion
#创建迁移文件执行后生成

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xid', models.IntegerField()),
                ('xschool', models.CharField(max_length=20)),
                ('xgrade', models.CharField(max_length=20)),
                ('xclass', models.CharField(max_length=20)),
                ('xname', models.CharField(max_length=20)),
                ('xage', models.IntegerField()),
                ('xgender', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pp_start_time', models.DateField()),
                ('pp_long', models.IntegerField()),
                ('pstart_time', models.DateField()),
                ('pover_time', models.DateField()),
                ('plong', models.IntegerField()),
                ('pscore', models.IntegerField()),
                ('pstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Students')),
            ],
        ),
    ]
